### ISSUE TITLE
"python manage.py migrate" not working for me

### ISSUE THREAD

**Issue by StrawHatAaron** [heroku/python-getting-started#67]
aaronmiller$ pip list
Package         Version
--------------- -------
dj-database-url 0.5.0  
Django                1.11.17
django-heroku   0.3.1  
gunicorn            19.9.0 
pip                      18.1   
psycopg2           2.7.6.1
pytz                    2018.7 
setuptools        39.2.0 
wheel               0.31.1 
whitenoise      4.1.2  

Python 2.7.15 and 3.7.2

ANYWAYS. When I do:

python manage.py migrate

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/aaronmiller/Development/python-getting-started/gettingstarted/settings.py", line 14, in <module>
    import django_heroku
  File "/usr/local/lib/python2.7/site-packages/django_heroku/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python2.7/site-packages/django_heroku/core.py", line 45
    def settings(config, *, db_colors=False, databases=True, test_runner=True, staticfiles=True, allowed_hosts=True, logging=True, secret_key=True):
                          ^
SyntaxError: invalid syntax

I would really like any ideas. I am new to python and am trying to warm up to it by doing this.

**Comment by StrawHatAaron** [comment]
which psql
/Applications/Postgres.app/Contents/Versions/latest/bin/psql

**Comment by bikemule** [comment]
This is months late, but looks like you are trying to run this on Python 2.7 when I think it is meant for Python 3.

From the [Python 3 docs](https://docs.python.org/3/reference/compound_stmts.html#function-definitions):

> Parameters after “*” or “*identifier” are keyword-only parameters and may only be passed used keyword arguments.

**Comment by edmorley** [comment]
@bikemule thank you for the help here. Agree this looks like an issue due to running on Python 2.7 instead.

Closing out since this issue was filed a while ago and will be fixed by updating the app to use Python 3.
